/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaVisuelsRouteImport } from './routes/qa-visuels'
import { Route as QuestionsRouteImport } from './routes/questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaVisuelsRoute = QaVisuelsRouteImport.update({
  id: '/qa-visuels',
  path: '/qa-visuels',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/questions': typeof QuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/questions': typeof QuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/questions': typeof QuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qa-visuels' | '/questions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qa-visuels' | '/questions'
  id: '__root__' | '/' | '/qa-visuels' | '/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QaVisuelsRoute: typeof QaVisuelsRoute
  QuestionsRoute: typeof QuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-visuels': {
      id: '/qa-visuels'
      path: '/qa-visuels'
      fullPath: '/qa-visuels'
      preLoaderRoute: typeof QaVisuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QaVisuelsRoute: QaVisuelsRoute,
  QuestionsRoute: QuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
