/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as ElevationRouteImport } from './routes/elevation'
import { Route as QaVisuelsRouteImport } from './routes/qa-visuels'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as ApiPublicRappelsRouteImport } from './routes/api/public/rappels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevationRoute = ElevationRouteImport.update({
  id: '/elevation',
  path: '/elevation',
  getParentRoute: () => rootRouteImport,
} as any)
const QaVisuelsRoute = QaVisuelsRouteImport.update({
  id: '/qa-visuels',
  path: '/qa-visuels',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRappelsRoute = ApiPublicRappelsRouteImport.update({
  id: '/api/public/rappels',
  path: '/api/public/rappels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/elevation': typeof ElevationRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/reglages': typeof ReglagesRoute
  '/api/public/rappels': typeof ApiPublicRappelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/elevation': typeof ElevationRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/reglages': typeof ReglagesRoute
  '/api/public/rappels': typeof ApiPublicRappelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corpus': typeof CorpusRoute
  '/elevation': typeof ElevationRoute
  '/qa-visuels': typeof QaVisuelsRoute
  '/reglages': typeof ReglagesRoute
  '/api/public/rappels': typeof ApiPublicRappelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corpus'
    | '/elevation'
    | '/qa-visuels'
    | '/reglages'
    | '/api/public/rappels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corpus'
    | '/elevation'
    | '/qa-visuels'
    | '/reglages'
    | '/api/public/rappels'
  id:
    | '__root__'
    | '/'
    | '/corpus'
    | '/elevation'
    | '/qa-visuels'
    | '/reglages'
    | '/api/public/rappels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorpusRoute: typeof CorpusRoute
  ElevationRoute: typeof ElevationRoute
  QaVisuelsRoute: typeof QaVisuelsRoute
  ReglagesRoute: typeof ReglagesRoute
  ApiPublicRappelsRoute: typeof ApiPublicRappelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elevation': {
      id: '/elevation'
      path: '/elevation'
      fullPath: '/elevation'
      preLoaderRoute: typeof ElevationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-visuels': {
      id: '/qa-visuels'
      path: '/qa-visuels'
      fullPath: '/qa-visuels'
      preLoaderRoute: typeof QaVisuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rappels': {
      id: '/api/public/rappels'
      path: '/api/public/rappels'
      fullPath: '/api/public/rappels'
      preLoaderRoute: typeof ApiPublicRappelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorpusRoute: CorpusRoute,
  ElevationRoute: ElevationRoute,
  QaVisuelsRoute: QaVisuelsRoute,
  ReglagesRoute: ReglagesRoute,
  ApiPublicRappelsRoute: ApiPublicRappelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
